/*
 *  Copyright (c) 2008 - Tomas Janecek.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
package songer.gui;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;



/**
 * TextDialog used for entrering of text - the dialog ensures that the input text matches the predefined regexp.
 * @author  Tomas Janecek
 */
public class TextDialog extends javax.swing.JDialog {
	/** Status information indicating whether the dialog was closed with OK or Cancel button. */
	private boolean okPressed;

	/** Pattern which the entered text has to match. */
	private Pattern pattern;

	
	
	/** 
	 * Creates new form TextDialog with the specified parameters.
	 * @param parent      Parent frame
	 * @param title       Title of the dialog.
	 * @param description Descrition of the text which should be entered.
	 */
	public TextDialog(java.awt.Frame parent, String title, String description) {
		super(parent, true);
		initComponents();
		setTitle(title);
		setResizable(false);
		label.setText(description);
	}

	
	
	/** Retruns the text in the text field. */
	public String getText() {
		return textField.getText();
	}

	
	
	/** 
	 * Runs the dialog - USE ONLY THIS TO START THE DIALOG.
	 * @param regexp The regular expresstion which the entered text must match in order to be accepted.
	 * @return TRUE if dialog was closed with OK button and the text was verified against the regexp; FALSE otherwise.
	 */
	public boolean runDialog(String regexp) {
		okPressed = false;
		textField.setText("");
		pattern = Pattern.compile(regexp);
		setVisible(true);
		return okPressed;
	}

	
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        okBT = new javax.swing.JButton();
        cancelBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label.setText("Label");

        okBT.setText("OK");
        okBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTActionPerformed(evt);
            }
        });

        cancelBT.setText("Cancel");
        cancelBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(okBT)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBT)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBT)
                    .addComponent(cancelBT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	
	
	/** Event handler of OK-button. */
    private void okBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTActionPerformed
		Matcher matcher = pattern.matcher(getText());
		if (!matcher.matches()) {
			JOptionPane.showMessageDialog(this, "Invalid text supplied - must match the regexp:\n\n\"" + pattern.pattern() + "\"", "ERROR", JOptionPane.ERROR_MESSAGE);
			return;
		}

		okPressed = true;
		this.setVisible(false);
    }//GEN-LAST:event_okBTActionPerformed

	
	
	/** Event handler of CANCEL-button. */
    private void cancelBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTActionPerformed
		okPressed = false;
		this.setVisible(false);
    }//GEN-LAST:event_cancelBTActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBT;
    private javax.swing.JLabel label;
    private javax.swing.JButton okBT;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
